### ISSUE TITLE
What is the point of defining form blocks?

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#15]
Suppose I have this:
```
<template name="myInput">
   <input class="reactive-element" value="{{value}}">
   <p>{{#unless valid}}{{errorMessage}}{{/unless}}</p>
</template>

<template name="myFormBlock">
  <form>
    {{> UI.contentBlock
        data=data
        schema=schema
        schemaContext=__schemaContext__
        setValidatedValue=__setValidatedValue__
        submit=__submit__
        submitted=__submitted__
        loading=__loading__
        failed=__failed__
        success=__success__
    }}
    <p>
      <button type="submit">Submit</button>
    </p>
  </form>
</template>

ReactiveForms.createElement({
  template: 'myInput',
  validationEvent: 'keyup'
});

ReactiveForms.createForm({
  template: 'myFormBlock',
  submitType: 'normal'
});

<template name="myForm">
    {{#myFormBlock schema=schema action=action}}
      {{> myInput field='testField'}}
    {{/myFormBlock}}
</template>
```

What is the point of having the user defining myFormBlock?

Couldn't I just have the following?:

```
<template name="myInput">
   <input class="reactive-element" value="{{value}}">
   <p>{{#unless valid}}{{errorMessage}}{{/unless}}</p>
</template>

ReactiveForms.createElement({
  template: 'myInput',
  validationEvent: 'keyup'
});

<template name="myForm">
    {{#defineForm schema=schema action=action}}
      {{> myInput field='testField'}}
      <button type="submit">Submit</button>
    {{/defineForm}}
</template>
```

**Comment by jonjamz** [comment]
In your example, there's no form-level handling of state, only element-level.

There is a set of [helpers](https://github.com/meteortemplates/forms#form-block-template-helpers) available to form blocks that allow you to build custom form-level templates. Two different forms could end up looking very different based on where, when, and how you handle form-level state.

To remove `createForm` would mean you'd need to copy code every time you wanted to use the same type of form-level template with different input elements.

Also, with larger or more complicated forms, it's going to be much better UX to handle these form-level states in one place (similar to the live example I created) rather than just putting error messages on the elements.

**Comment by steph643** [comment]
I am not used to complex form workflows, and there is no doubt you know more than me in this field (as a matter of fact, I don't understand much about your live example). But let me please push a little bit :-)

What I like in your package is its straightforwardness and I am exploring it with very simple use cases in mind. The first reason is that I only need simple use cases in my app. The second one is that I am convinced you attract people with simple use cases. If they get caught, then only they explore complex ones.

I have updated my example above with simple form-level handling of state (see the submit button). As you can see, there would be no code duplication if I wanted to use the same form with different input elements.

So my questions are:
1- Do you confirm there is no way to remove `myFormBlock` for simple use cases? (cases where there would be no - or minimal - code duplication) It implies being able to call `{{#if invalidCount}}` from inside `#defineForm`.
2- If there is no way to achieve this, is there a way to avoid the ugly `UI.contentBlock` line for simple use cases?

**Comment by jonjamz** [comment]
Thanks, I think the best way to solve this would be to automatically create a form block called `defineForm` or even `defaultForm` with the code you have in your example. 

Right now we have the `basicForm` example [here](https://github.com/meteortemplates/forms/blob/master/templates:forms.html), but it's not registered by default.

Perhaps this would help the onboarding process with the package, and when someone needed to proceed to more complex use cases we could take them through creating a custom form.

**Comment by jonjamz** [comment]
Another way to make the `UI.contentBlock` look less ugly is to consolidate all the helpers into one object like:

```handlebars
{{> UI.contentBlock
      data=data
      config=config
}}
```

Where `config` contains `config.schema`, `config.submit`, and so on.

**Comment by steph643** [comment]
> Another way to make the UI.contentBlock look less ugly is to consolidate all the helpers into one object [...] where config contains config.schema, config.submit, and so on.

I think that would be a good move.

**Comment by steph643** [comment]
> See how I passed in the invalidCount helper. I'm not 100% sure if this would work, but if it does, the other helpers should be able to be passed in as well. And then you can put the submit button inside the UI.contentBlock area like in your example, and because the form will still trigger submit regardless of where that button is, as long as it's between the <form></form> tags.

I tried that a few days ago and faced strange issues. I think it was about reactivity being triggered too much. I will investigate and post here.

If people have to pass in every user-defined helper as arguments to `defaultForm`, it is not so cool. I will try and see how it looks.

**Comment by steph643** [comment]
Here is the reactivity issue I was taking about: https://github.com/meteortemplates/forms/issues/17.

**Comment by jonjamz** [comment]
I believe I've found a solution to this. Will push it with the next update.

**Comment by jonjamz** [comment]
You can now do this with >`1.8.0` and reactivity will function properly. 

Here's how, using your example:

```handlebars
<template name="myForm">
    {{#defaultFormBlock schema=schema action=action}}
      {{> myInput field='testField'}}
      {{#with context}}
        <button type="submit" disabled="{{#if invalidCount}}disabled{{/if}}">Submit</button>
      {{/with}}
    {{/defaultFormBlock}}
</template>
```

Feel free to test this out and let me know how it goes!

**Comment by steph643** [comment]
This does not seem to work for me. I get the following error:

```
Uncaught TypeError: Cannot read property 'invalidKeys' of undefined      helpers.coffee:16
    invalidCount                                                         helpers.coffee:16
    (anonymous function)                                                     lookup.js:122
    ...
```

I am facing another issue, which might be related: 

With the former version, I used to access the schema from my element, like this:
```html
<template name="bootstrapInput">
    ...
    <label class="control-label">{{label}}{{#if th_isMandatory}} - Required</label>
    ...
</template>
```
```javascript
Template.bootstrapInput.helpers({
    th_isMandatory: function() {
        return !Template.parentData().schema._schema[this.field].optional;
    }
});
```
But now I cannot find the schema anywhere...

**Comment by jonjamz** [comment]
Looking into this.

**Comment by jonjamz** [comment]
I wasn't able to reproduce the `invalidKeys` error. Are you sure you're using the `{{#with context}}` block around the helper?

The `th_isMandatory` code doesn't work anymore because I've namespaced the component's properties in the template instance (since they're all inside the single `context` property now).

I was able to get this to work:

```javascript
Template.bootstrapInput.helpers({
    th_isMandatory: function() {
        return !Template.parentData().context.schema._schema[this.field].optional;
    }
});
```

**Comment by steph643** [comment]
Thanks, `th_isMandatory` works correctly when I define a custom form block.

But I confirm the 2 issues when using `defaultFormBlock`:
1. In `th_isMandatory`, `context` does not contain a `schema` field.
2. Still the same error: *Uncaught TypeError: Cannot read property 'invalidKeys' of undefined*.

Here are 2 sample code that trigger the error:

-1-
```html
<head>
  <title>form</title>
</head>

<body>
  <h1>Form</h1>
  {{#defaultFormBlock}}
      {{#with context}}
          {{invalidCount}}
      {{/with}}
  {{/defaultFormBlock}}
</body>
```

-2-
```html
<head>
  <title>form</title>
</head>

<body>
  <h1>Form</h1>
  {{> myForm}}
</body>

<template name="myForm">
    {{#defaultFormBlock schema=getSchema}}
        {{#with context}}
            {{invalidCount}}
        {{/with}}
    {{/defaultFormBlock}}
</template>
```
```javascript

	Template.myForm.helpers({
			
	  getSchema: function () {
		return new SimpleSchema({
		  testField1: {
			type: String,
			max: 3
		  },
		  testField2: {
			type: String,
			max: 3
		  },
		  testField3: {
			type: String,
			max: 3
		  }
		});
	  },
	});
```

I must be doing something silly...

**Comment by jonjamz** [comment]
I was able to reproduce the error with `defaultFormBlock` and I'll try to have this sorted out ASAP.

**Comment by jonjamz** [comment]
Ah--turns out I forgot to include `lib/init.coffee` in `package.js`, so `defaultFormBlock` was never registered.

**Comment by jonjamz** [comment]
Should be fixed now.

**Comment by steph643** [comment]
It works now, thanks.

Here is how I prefer to use `context`:
```html
<template name="myForm">
    {{#defaultFormBlock schema=getSchema action=action data=data}}
        ...
        <button type="submit" disabled="{{#if context.invalidCount}}disabled{{/if}}">Submit</button>
    {{/defaultFormBlock}}
</template>
```
I think there is no need to remove `context`, but it should probably be renamed into `helpers`, `formHelpers` or something...

I am still not convinced by the term `defaultFormBlock`. I'll try to think about something and update my documentation draft to show how it could look.

**Comment by steph643** [comment]
See the new draft here:
https://github.com/steph643/meteor-issue-3194/blob/master/old/README2.md

Assumptions:
- I used the term `formModel` instead of `formBlock`. I think my boostrapModal example shows why it makes sense.
- `basicFormModel` and  `basicInput` are pre-registered components.
- For the user, the submit button can be freely placed in the form model or the form itself, without having to think about it (same thing for package-provided helpers).
- New function names: `JonjamzForms.registerElement` and `JonjamzForms.registerModel`
